export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const ACCOUNTS_ID = process.env.NEXT_PUBLIC_APPWRITE_ACCOUNTS_ID!;
export const VEHICLES_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLES_ID!;

export const VEHICLE_MAKE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_MAKE_ID!;
export const VEHICLE_BODY_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_BODY_TYPE_ID!;
export const VEHICLE_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_TYPE_ID!;
export const VEHICLE_DRIVE_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_DRIVE_TYPE_ID!;
export const VEHICLE_PRIMARY_BODY_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_PRIMARY_BODY_TYPE_ID!;
export const VEHICLE_SIZE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_SIZE_ID!;
export const VEHICLE_MARKET_CLASS_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_MARKET_CLASS_ID!;
export const VEHICLE_EPA_CLASS_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_EPA_CLASS_ID!;
export const VEHICLE_ENGINE_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_ENGINE_TYPE_ID!;
export const VEHICLE_FUEL_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_FUEL_TYPE_ID!;
export const VEHICLE_COMPRESSOR_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_COMPRESSOR_TYPE_ID!;
export const VEHICLE_ENGINE_CONFIGURATION_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_ENGINE_CONFIGURATION_ID!;
export const VEHICLE_TRANSMISSION_TYPE_ID = process.env.NEXT_PUBLIC_APPWRITE_VEHICLE_TRANSMISSION_TYPE_ID!;